version: '3.3'

services:
    aerospike:
        image: aerospike/aerospike-server
        environment:
            AEROSPIKE_ENV: aerospike 
        networks:
        - aerospikenet
        deploy:
            mode: global
            endpoint_mode: dnsrr
        command: [ "/run/secrets/addtools.sh"]
        secrets:
        - source: conffile
          target: aerospike.conf
          mode: 0440
        - source: addtoolsfile 
          target:  addtools.sh 
          mode: 0750 
    
networks:
    aerospikenet:
        driver: overlay
        attachable: true

secrets:
    conffile:
        file: ./aerospike.conf
    addtoolsfile:
        file: ./addtools.sh
